---

# Set Host, Permission and project path
- name: Deploiement Cloud-1
  hosts: cloud_server
  become: yes
  vars:
    project_dest: "/home/ubuntu/app"

  tasks:
    - name: Update package manager
      apt:
        update_cache: yes
        cache_valid_time: 3600
    # Install packages and Docker
    - name: Install packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        state: present

    - name: Install Docker & Docker Compose
      apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present

    - name: Make nginx config directory
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ project_dest }}"
        - "{{ project_dest }}/nginx"
        - "{{ project_dest }}/nginx/conf.d"
        - "{{ project_dest }}/nginx/ssl"

    - name: Copy files to VM
      copy:
        src: "{{ item.src }}"
        dest: "{{ project_dest }}/{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: "./docker-compose.yml", dest: "docker-compose.yml" }
        - { src: "./.env", dest: ".env" }
        - { src: "./nginx/conf.d/default.conf", dest: "nginx/conf.d/default.conf" }

    - name: Generate SSL certificates
      command: >
        openssl req -x509 -noenc -days 365 -newkey rsa:2048
        -keyout {{ project_dest }}/nginx/ssl/key.pem
        -out {{ project_dest }}/nginx/ssl/cert.pem
        -subj "/C=FR/ST=IDF/L=Paris/O=42/CN=62.210.238.70"
      args:
        creates: "{{ project_dest }}/nginx/ssl/cert.pem"

    - name: Launch Docker Compose
      command: docker compose up -d
      args:
        chdir: "{{ project_dest }}"