version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    networks:
      - private_network
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    restart: always
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - private_network
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7
    networks:
      - private_network
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always

networks:
  private_network:
    driver: bridge

volumes:
  wordpress_data:
  db_data:
