- hosts: localhost
  become: yes
  tasks:
    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
        chdir: /home/devuser

